pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building the application...'
            }
        }
        stage('Approval Required') {
            steps {
                input "Approve Deployment?"
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying to production!'
            }
        }
    }
}