pipeline {
    agent any
    stages {
        stage('Deploy to Production') {
            when {
                branch 'main'
            }
            steps {
                echo 'Deploying application to production!'
            }
        }
    }
}